# Generated by Django 5.2.16 on 2026-08-03

import notifications.config
from django.db import migrations, models


def deactivate_duplicate_configurations(apps, schema_editor):
    EmailConfiguration = apps.get_model('notifications', 'EmailConfiguration')
    active_ids = list(
        EmailConfiguration.objects.filter(is_active=True)
        .order_by('-updated_at', '-created_at')
        .values_list('id', flat=True)
    )
    if len(active_ids) > 1:
        EmailConfiguration.objects.filter(id__in=active_ids[1:]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='config',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Non-sensitive configuration such as the default sender address.',
                validators=[notifications.config.validate_email_configuration],
            ),
        ),
        migrations.RunPython(
            deactivate_duplicate_configurations,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='emailconfiguration',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('is_active',),
                name='notifications_one_active_email_configuration',
            ),
        ),
    ]
