# Generated by Django 5.2.17 on 2026-08-06 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_harden_email_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT_POSTED', 'Assignment Posted'), ('DEADLINE_EXTENDED', 'Deadline Extended'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('assignment_id', models.UUIDField(blank=True, null=True)),
                ('course_id', models.BigIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=512, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Notification',
                'verbose_name_plural': 'In-App Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4a51a1_idx')],
            },
        ),
    ]
