# Generated by Django 5.2.17 on 2026-08-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_inappnotification'),
        ('portal_auth', '0004_alter_portaluser_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='portal_auth.portaluser'),
        ),
    ]
