# Generated by Django 5.2.8 on 2026-02-18 14:26
# The Django app label remains "content".

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('portal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_auth.portaluser'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to='portal_auth.portaluser'),
        ),
    ]
