"""Excel report builders for staff quiz and assessment gradebooks."""

from __future__ import annotations

from collections import defaultdict
from decimal import Decimal
from html import unescape
from io import BytesIO
import re

from django.http import HttpResponse
from django.utils.html import strip_tags
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


EXCEL_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
HEADER_FILL = PatternFill("solid", fgColor="064E3B")
SUBHEADER_FILL = PatternFill("solid", fgColor="D1FAE5")


def clean_text(value) -> str:
    """Turn saved rich text into readable report cell content."""
    return re.sub(r"\s+", " ", unescape(strip_tags(str(value or "")))).strip()


def safe_filename(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip(".-") or "report"


def excel_response(workbook: Workbook, filename: str) -> HttpResponse:
    stream = BytesIO()
    workbook.save(stream)
    response = HttpResponse(stream.getvalue(), content_type=EXCEL_CONTENT_TYPE)
    response["Content-Disposition"] = f'attachment; filename="{safe_filename(filename)}.xlsx"'
    return response


def select_report_attempt(attempts):
    """Select the best scored attempt, or the newest active attempt when none is graded."""
    if not attempts:
        return None

    return max(
        attempts,
        key=lambda attempt: (
            attempt.total_score is not None,
            Decimal(str(attempt.total_score or 0)),
            attempt.attempt_number,
            attempt.started_at,
        ),
    )


def _style_header(sheet, row_number: int, values: list[str]):
    for column, value in enumerate(values, start=1):
        cell = sheet.cell(row=row_number, column=column, value=value)
        cell.fill = HEADER_FILL
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(vertical="center")


def _fit_columns(sheet):
    for column_cells in sheet.columns:
        width = max((len(str(cell.value or "")) for cell in column_cells), default=10)
        sheet.column_dimensions[get_column_letter(column_cells[0].column)].width = min(max(width + 2, 12), 56)


def _question_snapshot(question_attempt):
    return getattr(question_attempt, "question_snapshot", {}) or {}


def _question_text(question_attempt) -> str:
    snapshot = _question_snapshot(question_attempt)
    return clean_text(snapshot.get("question_text") or question_attempt.question.question_text)


def _question_name(question_attempt) -> str:
    snapshot = _question_snapshot(question_attempt)
    return clean_text(snapshot.get("name") or question_attempt.question.name)


def _question_type(question_attempt) -> str:
    snapshot = _question_snapshot(question_attempt)
    return snapshot.get("qtype") or question_attempt.question.qtype


def _response_text(question_attempt) -> str:
    response = question_attempt.response or {}
    if response.get("text"):
        return clean_text(response["text"])

    selected = response.get("selected")
    selected_ids = selected if isinstance(selected, list) else [selected] if selected else []
    if not selected_ids:
        return "No response saved"

    snapshot = _question_snapshot(question_attempt)
    answers = snapshot.get("answers") or [
        {"id": str(answer.id), "answer_text": answer.answer_text}
        for answer in question_attempt.question.answers.all()
    ]
    answer_labels = {
        str(answer["id"]): clean_text(answer.get("answer_text"))
        for answer in answers
    }
    return ", ".join(answer_labels.get(str(answer_id), "Selected option") for answer_id in selected_ids)


def _set_title(sheet, title: str, subtitle: str):
    sheet["A1"] = title
    sheet["A1"].font = Font(size=16, bold=True, color="064E3B")
    sheet["A2"] = subtitle
    sheet["A2"].font = Font(italic=True, color="4B5563")


def _write_summary_sheet(workbook: Workbook, *, title: str, course_code: str, item_name: str, max_grade, student_count: int):
    sheet = workbook.active
    sheet.title = "Summary"
    _set_title(sheet, title, "Generated by ODEL LMS")
    rows = [
        ("Course", course_code),
        ("Activity", item_name),
        ("Maximum score", max_grade),
        ("Students included", student_count),
    ]
    for index, (label, value) in enumerate(rows, start=4):
        sheet.cell(index, 1, label).fill = SUBHEADER_FILL
        sheet.cell(index, 1).font = Font(bold=True, color="064E3B")
        sheet.cell(index, 2, value)
    _fit_columns(sheet)


def build_class_report(*, kind: str, item_name: str, course_code: str, max_grade, student_ids, users, attempts) -> Workbook:
    """Create a course-wide score workbook for a quiz or assessment."""
    workbook = Workbook()
    grouped_attempts = defaultdict(list)
    for attempt in attempts:
        grouped_attempts[attempt.user_external_id].append(attempt)

    all_student_ids = sorted(set(student_ids) | set(grouped_attempts), key=str)
    _write_summary_sheet(
        workbook,
        title=f"{kind} score report",
        course_code=course_code,
        item_name=item_name,
        max_grade=max_grade,
        student_count=len(all_student_ids),
    )

    sheet = workbook.create_sheet("Scores")
    _set_title(sheet, f"{kind} scores", item_name)
    headers = [
        "Student ID", "Student name", "Email", "Attempt state", "Attempts", "Selected attempt",
        "Score", "Maximum score", "Percentage", "Started at", "Submitted at",
    ]
    _style_header(sheet, 4, headers)
    for row_number, student_id in enumerate(all_student_ids, start=5):
        user = users.get(student_id)
        student_attempts = grouped_attempts.get(student_id, [])
        attempt = select_report_attempt(student_attempts)
        if attempt is None:
            row = [student_id, getattr(user, "full_name", ""), getattr(user, "email", ""), "No attempt", 0, "", "", max_grade, "", "", ""]
        else:
            score = attempt.total_score
            percentage = (Decimal(str(score)) / Decimal(str(attempt.grade_scale if hasattr(attempt, "grade_scale") else max_grade)) * 100) if score is not None else None
            max_score = getattr(attempt, "grade_scale", max_grade)
            row = [
                student_id, getattr(user, "full_name", ""), getattr(user, "email", ""),
                attempt.get_state_display(), len(student_attempts), attempt.attempt_number,
                score, max_score, percentage, attempt.started_at, attempt.finished_at,
            ]
        for column, value in enumerate(row, start=1):
            sheet.cell(row_number, column, value)
        sheet.cell(row_number, 7).number_format = "0.00"
        sheet.cell(row_number, 8).number_format = "0.00"
        sheet.cell(row_number, 9).number_format = "0.0"
        for column in (10, 11):
            sheet.cell(row_number, column).number_format = "yyyy-mm-dd hh:mm"
    sheet.freeze_panes = "A5"
    sheet.auto_filter.ref = f"A4:K{max(sheet.max_row, 4)}"
    _fit_columns(sheet)
    return workbook


def build_student_report(*, kind: str, item_name: str, course_code: str, user, attempt, question_marks=None) -> Workbook:
    """Create a detailed individual report, including saved responses and marks."""
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Student report"
    _set_title(sheet, f"{kind} student report", item_name)
    maximum_score = getattr(attempt, "grade_scale", None) or getattr(attempt.quiz, "max_grade", None)
    score = attempt.total_score
    rows = [
        ("Course", course_code),
        ("Student ID", attempt.user_external_id),
        ("Student name", getattr(user, "full_name", "")),
        ("Email", getattr(user, "email", "")),
        ("Attempt", attempt.attempt_number),
        ("State", attempt.get_state_display()),
        ("Score", score),
        ("Maximum score", maximum_score),
        ("Percentage", (Decimal(str(score)) / Decimal(str(maximum_score)) * 100) if score is not None and maximum_score else None),
        ("Started at", attempt.started_at),
        ("Submitted at", attempt.finished_at),
    ]
    for index, (label, value) in enumerate(rows, start=4):
        sheet.cell(index, 1, label).fill = SUBHEADER_FILL
        sheet.cell(index, 1).font = Font(bold=True, color="064E3B")
        sheet.cell(index, 2, value)
    for row_number in (10, 11, 12):
        sheet.cell(row_number, 2).number_format = "0.00" if row_number != 12 else "0.0"
    for row_number in (13, 14):
        sheet.cell(row_number, 2).number_format = "yyyy-mm-dd hh:mm"
    _fit_columns(sheet)

    responses = workbook.create_sheet("Responses")
    _set_title(responses, "Saved responses", item_name)
    _style_header(responses, 4, ["Order", "Question", "Question text", "Type", "Student response", "Score", "Maximum mark", "Feedback"])
    question_marks = question_marks or {}
    question_attempts = sorted(attempt.question_attempts.all(), key=lambda value: value.display_order)
    for row_number, question_attempt in enumerate(question_attempts, start=5):
        values = [
            question_attempt.display_order,
            _question_name(question_attempt),
            _question_text(question_attempt),
            _question_type(question_attempt),
            _response_text(question_attempt),
            question_attempt.score,
            getattr(question_attempt, "max_mark", None) or question_marks.get(str(question_attempt.question_id)),
            clean_text(question_attempt.feedback),
        ]
        for column, value in enumerate(values, start=1):
            cell = responses.cell(row_number, column, value)
            cell.alignment = Alignment(vertical="top", wrap_text=column in (3, 5, 8))
        responses.cell(row_number, 6).number_format = "0.00"
        responses.cell(row_number, 7).number_format = "0.00"
    responses.freeze_panes = "A5"
    responses.auto_filter.ref = f"A4:H{max(responses.max_row, 4)}"
    _fit_columns(responses)
    return workbook
