# Generated by Django 5.2.8 on 2025-12-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('mode_of_entry', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level')], help_text='Entry level (100, 200, or 300)', max_length=10)),
                ('sitting_type', models.CharField(choices=[('one', 'One Sitting'), ('two', 'Two Sittings')], default='one', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('failed_verification', 'Failed Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='users.applicant')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='programmes.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('GCE', 'GCE'), ('NECO_GCE', 'NECO GCE')], max_length=20)),
                ('exam_year', models.IntegerField(help_text='Year exam was taken')),
                ('exam_number', models.CharField(help_text='Examination number', max_length=50)),
                ('scratch_card_pin', models.CharField(blank=True, help_text='Scratch card PIN for verification', max_length=50)),
                ('sitting_number', models.IntegerField(choices=[(1, 'First Sitting'), (2, 'Second Sitting')], default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='admissions.application')),
            ],
            options={
                'ordering': ['sitting_number'],
                'unique_together': {('application', 'sitting_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A1', 'A1 - Excellent'), ('B2', 'B2 - Very Good'), ('B3', 'B3 - Good'), ('C4', 'C4 - Credit'), ('C5', 'C5 - Credit'), ('C6', 'C6 - Credit'), ('D7', 'D7 - Pass'), ('E8', 'E8 - Pass'), ('F9', 'F9 - Fail')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='admissions.examresult')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
