# Generated by Django 5.2.8 on 2025-12-01 10:02

from django.db import migrations


def populate_application_ids(apps, schema_editor):
    """Generate application_id for existing applications"""
    Application = apps.get_model('admissions', 'Application')
    from datetime import datetime
    
    current_year = datetime.now().year % 100
    year_prefix = f'app{current_year:02d}'
    
    for index, application in enumerate(Application.objects.filter(application_id=''), start=1):
        application.application_id = f'{year_prefix}{index:04d}'
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_application_application_id_application_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_application_ids, reverse_code=migrations.RunPython.noop),
    ]
