# Generated by Django 5.2.8 on 2025-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_populate_application_ids'),
        ('programmes', '0001_initial'),
        ('users', '0002_applicant_mode_of_entry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'is_active'], name='admissions__applica_074f35_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('applicant',), name='unique_active_application_per_applicant'),
        ),
    ]
