# Generated by Django 5.2.8 on 2026-01-02 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtype', models.CharField(choices=[('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('essay', 'Essay')], db_index=True, max_length=32)),
                ('name', models.CharField(help_text='Internal name for question management', max_length=255)),
                ('question_text', models.TextField(help_text='Question text (supports HTML)')),
                ('general_feedback', models.TextField(blank=True, help_text='Feedback shown after answering')),
                ('default_mark', models.DecimalField(decimal_places=2, default=1.0, help_text='Default points for this question', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty factor for wrong attempts (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('version', models.IntegerField(default=1, help_text='Question version for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('open_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Null means unlimited attempts', null=True)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('max_marks', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum marks for this assignment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.coursecache')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('instruction', 'Instruction'), ('resource', 'Resource'), ('example', 'Example')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('storage_path', models.CharField(db_index=True, max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_published', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='assessment.assignment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_external_id', models.CharField(db_index=True, max_length=255)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('reopened', 'Reopened')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Final score for this submission attempt', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment.assignmentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('fraction', models.DecimalField(decimal_places=2, help_text='Grade fraction: 1.0=correct, 0.5=partial, 0.0=wrong, -1.0=penalty', max_digits=3, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, help_text='Feedback for this answer option')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('all', 'All Levels')], default='all', help_text='Educational level for questions in this category (100-500)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='courses.coursecache')),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questioncategory'),
        ),
        migrations.CreateModel(
            name='QuestionTypeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('all', 'All Levels')], db_index=True, help_text='Educational level this setting applies to', max_length=50)),
                ('question_type', models.CharField(choices=[('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('essay', 'Essay')], db_index=True, help_text='Type of question', max_length=32)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this question type is enabled for this level')),
                ('description', models.TextField(blank=True, help_text='Optional description or reason for this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_type_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Type Availability',
                'verbose_name_plural': 'Question Type Availabilities',
                'ordering': ['level', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_open', models.DateTimeField(blank=True, help_text='When quiz becomes available', null=True)),
                ('time_close', models.DateTimeField(blank=True, help_text='When quiz closes', null=True)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('max_grade', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum grade for this quiz', max_digits=10)),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Randomize question order')),
                ('max_attempts', models.IntegerField(default=1, help_text='Maximum attempts allowed (0 = unlimited)')),
                ('show_feedback', models.BooleanField(default=True, help_text='Show feedback after submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursecache')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.CharField(db_index=True, help_text='External user ID', max_length=255)),
                ('attempt_number', models.IntegerField(help_text='Attempt number for this user/quiz')),
                ('state', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score for this attempt', max_digits=10, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField(default=dict, help_text='Student response (structure depends on question type)')),
                ('fraction', models.DecimalField(blank=True, decimal_places=2, help_text='Grade fraction (0.0-1.0)', max_digits=3, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Actual points earned (fraction × max_mark)', max_digits=10, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('manually_graded', models.BooleanField(default=False, help_text='True if manually graded (e.g., essays)')),
                ('feedback', models.TextField(blank=True, help_text='Specific feedback for this attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessment.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='assessment.quizattempt')),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': 'Question Attempts',
                'ordering': ['quiz_attempt', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_external_id', models.CharField(db_index=True, help_text='External student identifier', max_length=255)),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz')], db_index=True, help_text='Type of graded item', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Score earned by student', max_digits=10)),
                ('total_possible', models.DecimalField(decimal_places=2, help_text='Maximum possible score for this item', max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score (marks/total_possible × 100)', max_digits=5, null=True)),
                ('graded_at', models.DateTimeField(help_text='When the item was graded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_submission', models.ForeignKey(blank=True, help_text='Link to graded assignment submission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.assignmentsubmission')),
                ('course', models.ForeignKey(help_text='Course this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.coursecache')),
                ('quiz_attempt', models.ForeignKey(blank=True, help_text='Link to graded quiz attempt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.quizattempt')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Question order in quiz')),
                ('max_mark', models.DecimalField(decimal_places=2, help_text='Maximum points for this question in this quiz (can override default_mark)', max_digits=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_slots', to='assessment.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='assessment.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question Slot',
                'verbose_name_plural': 'Quiz Question Slots',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assessment__course__e52680_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['open_at', 'due_at'], name='assessment__open_at_15b436_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcontent',
            index=models.Index(fields=['assignment', 'content_type'], name='assessment__assignm_6e872c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student_external_id'], name='assessment__assignm_887916_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student_external_id', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='questioncategory',
            unique_together={('course', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'qtype'], name='assessment__categor_259933_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='assessment__created_ae046b_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontypeavailability',
            index=models.Index(fields=['level', 'is_enabled'], name='assessment__level_f33968_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontypeavailability',
            index=models.Index(fields=['question_type', 'is_enabled'], name='assessment__questio_5b8279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontypeavailability',
            unique_together={('level', 'question_type')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user_external_id', '-attempt_number'], name='assessment__quiz_id_6cde03_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['state', 'started_at'], name='assessment__state_a34615_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user_external_id', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('quiz_attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_external_id', 'course'], name='assessment__student_f59844_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'grade_type'], name='assessment__course__cc6e94_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_external_id', 'course', 'grade_type'], name='assessment__student_702632_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_submission__isnull', False)), fields=('assignment_submission',), name='unique_assignment_submission_grade'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_attempt__isnull', False)), fields=('quiz_attempt',), name='unique_quiz_attempt_grade'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order'), ('quiz', 'question')},
        ),
    ]
