# Generated by Django 5.2.8 on 2025-12-13 16:58

import assessment.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtype', models.CharField(choices=[('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('essay', 'Essay')], db_index=True, max_length=32)),
                ('name', models.CharField(help_text='Internal name for question management', max_length=255)),
                ('question_text', models.TextField(help_text='Question text (supports HTML)')),
                ('general_feedback', models.TextField(blank=True, help_text='Feedback shown after answering')),
                ('default_mark', models.DecimalField(decimal_places=2, default=1.0, help_text='Default points for this question', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty factor for wrong attempts (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('version', models.IntegerField(default=1, help_text='Question version for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.classroom')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('fraction', models.DecimalField(decimal_places=2, help_text='Grade fraction: 1.0=correct, 0.5=partial, 0.0=wrong, -1.0=penalty', max_digits=3, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('feedback', models.TextField(blank=True, help_text='Feedback for this answer option')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='courses.coursecache')),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
                'ordering': ['name'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questioncategory'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_open', models.DateTimeField(blank=True, help_text='When quiz becomes available', null=True)),
                ('time_close', models.DateTimeField(blank=True, help_text='When quiz closes', null=True)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('max_grade', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum grade for this quiz', max_digits=10)),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Randomize question order')),
                ('max_attempts', models.IntegerField(default=1, help_text='Maximum attempts allowed (0 = unlimited)')),
                ('show_feedback', models.BooleanField(default=True, help_text='Show feedback after submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursecache')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_external_id', models.CharField(db_index=True, help_text='External user ID', max_length=255)),
                ('attempt_number', models.IntegerField(help_text='Attempt number for this user/quiz')),
                ('state', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score for this attempt', max_digits=10, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField(default=dict, help_text='Student response (structure depends on question type)')),
                ('fraction', models.DecimalField(blank=True, decimal_places=2, help_text='Grade fraction (0.0-1.0)', max_digits=3, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Actual points earned (fraction × max_mark)', max_digits=10, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('manually_graded', models.BooleanField(default=False, help_text='True if manually graded (e.g., essays)')),
                ('feedback', models.TextField(blank=True, help_text='Specific feedback for this attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessment.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='assessment.quizattempt')),
            ],
            options={
                'verbose_name': 'Question Attempt',
                'verbose_name_plural': 'Question Attempts',
                'ordering': ['quiz_attempt', 'question'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Question order in quiz')),
                ('max_mark', models.DecimalField(decimal_places=2, help_text='Maximum points for this question in this quiz (can override default_mark)', max_digits=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_slots', to='assessment.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='assessment.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question Slot',
                'verbose_name_plural': 'Quiz Question Slots',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_external_id', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=assessment.models.submission_upload_to)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assignment')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'qtype'], name='assessment__categor_259933_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='assessment__created_ae046b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user_external_id', '-attempt_number'], name='assessment__quiz_id_6cde03_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['state', 'started_at'], name='assessment__state_a34615_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user_external_id', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('quiz_attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order'), ('quiz', 'question')},
        ),
    ]
