# Generated by Django 5.2.8 on 2025-12-15 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assignment_classroom_assignment_course'),
        ('courses', '0002_remove_classroom_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('instruction', 'Instruction'), ('resource', 'Resource'), ('example', 'Example')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('storage_path', models.CharField(db_index=True, max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_published', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_external_id', models.CharField(db_index=True, max_length=255)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('reopened', 'Reopened')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Null means unlimited attempts', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='open_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course'], name='assessment__course__e52680_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['open_at', 'due_at'], name='assessment__open_at_15b436_idx'),
        ),
        migrations.AddField(
            model_name='assignmentcontent',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='assessment.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcontent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessment.assignmentsubmission'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddIndex(
            model_name='assignmentcontent',
            index=models.Index(fields=['assignment', 'content_type'], name='assessment__assignm_6e872c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student_external_id'], name='assessment__assignm_887916_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student_external_id', 'attempt_number')},
        ),
    ]
