# Generated by Django 5.2.8 on 2026-01-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assignment_created_by'),
        ('portal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcontent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_auth.portaluser'),
        ),
        migrations.AlterField(
            model_name='questiontypeavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_type_settings', to='portal_auth.portaluser'),
        ),
    ]
