# Generated by Django 5.2.8 on 2025-12-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assignmentcontent_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final score for this submission attempt', max_digits=6, null=True),
        ),
    ]
