# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assignment_submission_student_fk'),
    ]

    operations = [
        # Keep already-created quizzes visible; newly-created quizzes start as drafts.
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Only published quizzes are visible to enrolled students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published quizzes are visible to enrolled students'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Question position for this specific attempt'),
        ),
    ]
