# Generated by Django 5.2.8 on 2025-12-20 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assignmentsubmission_marks'),
        ('courses', '0002_remove_classroom_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum marks for this assignment', max_digits=10),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_external_id', models.CharField(db_index=True, help_text='External student identifier', max_length=255)),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz')], db_index=True, help_text='Type of graded item', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Score earned by student', max_digits=10)),
                ('total_possible', models.DecimalField(decimal_places=2, help_text='Maximum possible score for this item', max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score (marks/total_possible × 100)', max_digits=5, null=True)),
                ('graded_at', models.DateTimeField(help_text='When the item was graded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_submission', models.ForeignKey(blank=True, help_text='Link to graded assignment submission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.assignmentsubmission')),
                ('course', models.ForeignKey(help_text='Course this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.coursecache')),
                ('quiz_attempt', models.ForeignKey(blank=True, help_text='Link to graded quiz attempt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.quizattempt')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-graded_at'],
                'indexes': [models.Index(fields=['student_external_id', 'course'], name='assessment__student_f59844_idx'), models.Index(fields=['course', 'grade_type'], name='assessment__course__cc6e94_idx'), models.Index(fields=['student_external_id', 'course', 'grade_type'], name='assessment__student_702632_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assignment_submission__isnull', False)), fields=('assignment_submission',), name='unique_assignment_submission_grade'), models.UniqueConstraint(condition=models.Q(('quiz_attempt__isnull', False)), fields=('quiz_attempt',), name='unique_quiz_attempt_grade')],
            },
        ),
    ]
