# Generated by Django 5.2.8 on 2025-12-23 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assignment_max_marks_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('all', 'All Levels')], db_index=True, help_text='Educational level this setting applies to', max_length=50)),
                ('question_type', models.CharField(choices=[('multichoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('essay', 'Essay')], db_index=True, help_text='Type of question', max_length=32)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this question type is enabled for this level')),
                ('description', models.TextField(blank=True, help_text='Optional description or reason for this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_type_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Type Availability',
                'verbose_name_plural': 'Question Type Availabilities',
                'ordering': ['level', 'question_type'],
                'indexes': [models.Index(fields=['level', 'is_enabled'], name='assessment__level_f33968_idx'), models.Index(fields=['question_type', 'is_enabled'], name='assessment__questio_5b8279_idx')],
                'unique_together': {('level', 'question_type')},
            },
        ),
    ]
