# Generated by Django 5.2.8 on 2025-12-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_questiontypeavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('all', 'All Levels')], default='all', help_text='Educational level for questions in this category (100-500)', max_length=50),
        ),
    ]
