# Generated by Django 5.2.8 on 2026-01-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('course_title', models.CharField(max_length=512)),
                ('course_code', models.CharField(max_length=128)),
                ('credit_unit', models.FloatField(blank=True, null=True)),
                ('level', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('department_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_id', models.IntegerField(blank=True, null=True)),
                ('semester_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_title'],
            },
        ),
        migrations.CreateModel(
            name='StaffRegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_external_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_enrollments', to='courses.coursecache')),
            ],
            options={
                'indexes': [models.Index(fields=['staff_external_id'], name='courses_sta_staff_e_bc525f_idx'), models.Index(fields=['course'], name='courses_sta_course__c2a0b1_idx')],
                'unique_together': {('staff_external_id', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentRegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_external_id', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.PositiveIntegerField(db_index=True)),
                ('semester_id', models.PositiveIntegerField(db_index=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.coursecache')),
            ],
            options={
                'ordering': ['-course__course_title'],
                'unique_together': {('student_external_id', 'course', 'session_id', 'semester_id')},
            },
        ),
    ]
