# Generated by Django 5.2.8 on 2026-01-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffRegisteredCourse',
            new_name='StaffAssignedCourse',
        ),
        migrations.RenameIndex(
            model_name='staffassignedcourse',
            new_name='courses_sta_staff_e_f0610a_idx',
            old_name='courses_sta_staff_e_bc525f_idx',
        ),
        migrations.RenameIndex(
            model_name='staffassignedcourse',
            new_name='courses_sta_course__1e6854_idx',
            old_name='courses_sta_course__c2a0b1_idx',
        ),
    ]
