# Generated by Django 5.2.8 on 2025-12-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assignment_classroom_assignment_course'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='course',
        ),
        migrations.RenameIndex(
            model_name='enrollmentcache',
            new_name='courses_enr_user_ex_dc278f_idx',
            old_name='classroom_e_user_ex_117eaf_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollmentcache',
            new_name='courses_enr_course__e47681_idx',
            old_name='classroom_e_course__63a24c_idx',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
