# Generated by Django 5.2.16 on 2026-07-11 16:20

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_named_academic_periods_and_external_staff_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(Lower('name'), name='unique_academic_session_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(Lower('name'), name='unique_semester_name_ci')],
            },
        ),
    ]
