# Generated by Django 5.2.8 on 2026-01-02 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'Amazon S3'), ('cloudinary', 'Cloudinary'), ('youtube', 'YouTube')], default='local', help_text='Active storage backend. Credentials are loaded from environment variables.', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Settings',
                'verbose_name_plural': 'Storage Settings',
            },
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(default='learning_content', help_text='Component name (similar to Moodle components).', max_length=100)),
                ('content_type', models.CharField(choices=[('note', 'Lecture Note'), ('video', 'Video Lecture'), ('resource', 'Resource'), ('assignment', 'Assignment')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('storage_path', models.CharField(db_index=True, max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_backend', models.CharField(default='local', help_text='Backend where file is stored.', max_length=20)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for deduplication.', max_length=64)),
                ('is_published', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_contents', to='courses.coursecache')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='content.learningcontent')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['course', 'content_type'], name='content_lea_course__7b6002_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['content_hash'], name='content_lea_content_35c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningcontent',
            index=models.Index(fields=['course', 'content_type', 'is_published'], name='content_lea_course__49ce18_idx'),
        ),
        migrations.AddIndex(
            model_name='contentaccesslog',
            index=models.Index(fields=['content', 'accessed_at'], name='content_con_content_d69f42_idx'),
        ),
    ]
