# Generated by Django 5.2.8 on 2025-12-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., UG, PG, DIP, CERT', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Study Category',
                'verbose_name_plural': 'Study Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., BSc, BA, PGD, MSc, MBA, PhD', max_length=20)),
                ('name', models.CharField(help_text='Full name of degree', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_types', to='programmes.studycategory')),
            ],
            options={
                'ordering': ['category__code', 'code'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Programme name (e.g., Accounting, Computer Science)', max_length=200)),
                ('duration_years', models.IntegerField(default=4, help_text='Programme duration in years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='programmes.degreetype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='faculty.department')),
            ],
            options={
                'ordering': ['department__faculty__name', 'department__name', 'degree_type__code', 'name'],
                'unique_together': {('department', 'degree_type', 'name')},
            },
        ),
    ]
