# Generated by Django 5.2.16 on 2026-07-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_auth', '0002_portaluser_first_name_portaluser_last_name'),
        ('synchronization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='synchronization.programme'),
        ),
    ]
