# Generated by Django 5.2.8 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mode_of_entry',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level')], default='100', help_text='Entry level (100, 200, or 300)', max_length=10),
        ),
    ]
