# Generated by Django 5.1.7 on 2025-11-30 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique setting key (e.g., REQUIRE_EMAIL_VERIFICATION)', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Setting value (stored as text, converted based on type)')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('json', 'JSON')], default='string', help_text='Data type for proper conversion', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
                'ordering': ['key'],
            },
        ),
    ]
